#%RAML 1.0
title: jukeboxApi
mediaType: 
- application/json

/songs:
  get:
    queryParameters:
      songTitle: 
        description: "Song Title"
        required: true
        minLength: 3
        type: string
        example: "Get L"
    responses:
      200:
        body:
          application/json:
            example: !include Examples/response.json
  /{songId}:
    get:
      description: Get the song with `songId = <resourcePathName>